# Generated by Django 5.0.4 on 2024-06-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='story_counts',
            field=models.IntegerField(default=0),
        ),
    ]
