# Generated by Django 5.0.4 on 2024-06-19 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_special_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special_post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
    ]
